# Intrduction to NumPy


#### 1. Import NumPy under the name np.

Judith Torres Jiménez DSBI PGE 7

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [66]:
# your code here
np.__version__

'2.0.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [67]:
# Method 1
a = np.random.random((2,3,5))
print(a)

[[[0.79437299 0.80026612 0.45384412 0.85420942 0.81172417]
  [0.5234846  0.32177354 0.9779729  0.95198851 0.20113473]
  [0.99945064 0.59510453 0.58695947 0.43967231 0.17857562]]

 [[0.10698115 0.70639797 0.3916442  0.74672161 0.60019066]
  [0.10942719 0.78848173 0.18870859 0.64756642 0.58590562]
  [0.85547202 0.10174812 0.05781311 0.19599858 0.87410367]]]


In [68]:
# Method 2
a = np.random.rand(2,3,5)
print(a)


[[[0.21696103 0.81880155 0.82422835 0.0509468  0.19096628]
  [0.75231546 0.28111213 0.42367831 0.65436023 0.20851498]
  [0.96718424 0.44696162 0.06031124 0.15639953 0.48560562]]

 [[0.67199308 0.79297694 0.99139769 0.75781874 0.17480666]
  [0.06247591 0.44052898 0.38312065 0.18335037 0.34567058]
  [0.96878562 0.40073    0.12333008 0.4127617  0.43735658]]]


In [69]:
# Method 3
a = np.random.randn(2,3,5)
print(a)

[[[ 0.59024771 -0.28434294 -0.15364789 -0.97788497 -1.20195488]
  [ 0.20848047  0.08231027 -1.48962827 -1.61046271 -0.37624165]
  [ 0.3274095  -0.34892863 -0.65209425  0.20722593  0.0108311 ]]

 [[ 0.24662377 -0.58299637 -0.05176156 -0.14197112 -0.26264062]
  [-0.92881063 -0.18750058 -1.00077603  0.22358773  0.63361793]
  [ 0.23889815  0.80445073  0.50997045  0.74458254  0.18072313]]]


#### 4. Print *a*.


In [70]:
# your code here
print(a)

[[[ 0.59024771 -0.28434294 -0.15364789 -0.97788497 -1.20195488]
  [ 0.20848047  0.08231027 -1.48962827 -1.61046271 -0.37624165]
  [ 0.3274095  -0.34892863 -0.65209425  0.20722593  0.0108311 ]]

 [[ 0.24662377 -0.58299637 -0.05176156 -0.14197112 -0.26264062]
  [-0.92881063 -0.18750058 -1.00077603  0.22358773  0.63361793]
  [ 0.23889815  0.80445073  0.50997045  0.74458254  0.18072313]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [71]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [72]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [73]:
# your code here
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [74]:
# your answer here
# No, because they have the same size but not the same shape
z = a + b
z

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [75]:
# your code here
c = b.reshape(2,3,5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [77]:
# your code/ Now it works because they have the same shape and you can add them
d = a + c
print(d)

[[[ 1.59024771e+00  7.15657062e-01  8.46352108e-01  2.21150318e-02
   -2.01954885e-01]
  [ 1.20848047e+00  1.08231027e+00 -4.89628271e-01 -6.10462707e-01
    6.23758351e-01]
  [ 1.32740950e+00  6.51071366e-01  3.47905748e-01  1.20722593e+00
    1.01083110e+00]]

 [[ 1.24662377e+00  4.17003627e-01  9.48238438e-01  8.58028879e-01
    7.37359377e-01]
  [ 7.11893670e-02  8.12499420e-01 -7.76026168e-04  1.22358773e+00
    1.63361793e+00]
  [ 1.23889815e+00  1.80445073e+00  1.50997045e+00  1.74458254e+00
    1.18072313e+00]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [78]:
# your code/ They have the same shape, but the values in d are 1 value bigger.
print(a)
print(d)

[[[ 0.59024771 -0.28434294 -0.15364789 -0.97788497 -1.20195488]
  [ 0.20848047  0.08231027 -1.48962827 -1.61046271 -0.37624165]
  [ 0.3274095  -0.34892863 -0.65209425  0.20722593  0.0108311 ]]

 [[ 0.24662377 -0.58299637 -0.05176156 -0.14197112 -0.26264062]
  [-0.92881063 -0.18750058 -1.00077603  0.22358773  0.63361793]
  [ 0.23889815  0.80445073  0.50997045  0.74458254  0.18072313]]]
[[[ 1.59024771e+00  7.15657062e-01  8.46352108e-01  2.21150318e-02
   -2.01954885e-01]
  [ 1.20848047e+00  1.08231027e+00 -4.89628271e-01 -6.10462707e-01
    6.23758351e-01]
  [ 1.32740950e+00  6.51071366e-01  3.47905748e-01  1.20722593e+00
    1.01083110e+00]]

 [[ 1.24662377e+00  4.17003627e-01  9.48238438e-01  8.58028879e-01
    7.37359377e-01]
  [ 7.11893670e-02  8.12499420e-01 -7.76026168e-04  1.22358773e+00
    1.63361793e+00]
  [ 1.23889815e+00  1.80445073e+00  1.50997045e+00  1.74458254e+00
    1.18072313e+00]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [79]:
# your code here
e = a * c
print(e)

[[[ 0.59024771 -0.28434294 -0.15364789 -0.97788497 -1.20195488]
  [ 0.20848047  0.08231027 -1.48962827 -1.61046271 -0.37624165]
  [ 0.3274095  -0.34892863 -0.65209425  0.20722593  0.0108311 ]]

 [[ 0.24662377 -0.58299637 -0.05176156 -0.14197112 -0.26264062]
  [-0.92881063 -0.18750058 -1.00077603  0.22358773  0.63361793]
  [ 0.23889815  0.80445073  0.50997045  0.74458254  0.18072313]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [80]:
# your code/ Yes they are, because e[i][j][k] = a[i][j][k] and because before we multiplied a*1
e == a


array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [81]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
print(d_max, d_min, d_mean)

1.8044507345594658 -0.6104627073743281 0.8252438761298707


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [82]:
# your code here
f = np.empty((2,3,5))

#### 16. Populate the values in *f*.

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [83]:
f[d == d_min] = 0
f[(d > d_min) & (d < d_mean)] = 25
f[d == d_mean] = 50
f[(d > d_mean) & (d < d_max)] = 75
f[d == d_max] = 100


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [84]:
# your code here
print(d)
print(f)

[[[ 1.59024771e+00  7.15657062e-01  8.46352108e-01  2.21150318e-02
   -2.01954885e-01]
  [ 1.20848047e+00  1.08231027e+00 -4.89628271e-01 -6.10462707e-01
    6.23758351e-01]
  [ 1.32740950e+00  6.51071366e-01  3.47905748e-01  1.20722593e+00
    1.01083110e+00]]

 [[ 1.24662377e+00  4.17003627e-01  9.48238438e-01  8.58028879e-01
    7.37359377e-01]
  [ 7.11893670e-02  8.12499420e-01 -7.76026168e-04  1.22358773e+00
    1.63361793e+00]
  [ 1.23889815e+00  1.80445073e+00  1.50997045e+00  1.74458254e+00
    1.18072313e+00]]]
[[[ 75.  25.  75.  25.  25.]
  [ 75.  75.  25.   0.  25.]
  [ 75.  25.  25.  75.  75.]]

 [[ 75.  25.  75.  75.  25.]
  [ 25.  25.  25.  75.  75.]
  [ 75. 100.  75.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [90]:
# your code here
f_labels = np.empty_like(d, dtype=str)
f_labels[d == d_min] = "A"
f_labels[(d > d_min) & (d < d_mean)] = "B"
f_labels[d == d_mean] = "C"
f_labels[(d > d_mean) & (d < d_max)] = "D"
f_labels[d == d_max] = "E"

print(f_labels)

[[['D' 'B' 'D' 'B' 'B']
  ['D' 'D' 'B' 'A' 'B']
  ['D' 'B' 'B' 'D' 'D']]

 [['D' 'B' 'D' 'D' 'B']
  ['B' 'B' 'B' 'D' 'D']
  ['D' 'E' 'D' 'D' 'D']]]
